CITY_CHOICES = [
    ('Kiev', 'Киев'),
    ('Kharkiv', 'Харьков'),
    ('Odessa', 'Одесса'),
    ('Dnipro', 'Днепр'),
    ('Lviv', 'Львов'),
    ('Kyiv', 'Київ'),
    ('Donetsk', 'Донецк'),
    ('Zaporizhzhia', 'Запорожье'),
    ('Khmelnytskyi', 'Хмельницкий'),
    ('Vinnytsia', 'Винница'),
    ('Zhytomyr', 'Житомир'),
    ('Chernihiv', 'Чернигов'),
    ('Cherkasy', 'Черкасы'),
    ('Sumy', 'Сумы'),
    ('Poltava', 'Полтава'),
    ('Rivne', 'Ровно'),
    ('Uzhhorod', 'Ужгород'),
    ('Mykolaiv', 'Николаев'),
    ('Ternopil', 'Тернополь'),
    ('Kherson', 'Херсон'),
    ('Ivano-Frankivsk', 'Ивано-Франковск'),
    ('Lutsk', 'Луцк'),
    ('Melitopol', 'Мелитополь'),
    ('Kropyvnytskyi', 'Кропивницкий'),
    ('Berdiansk', 'Бердянск'),
    ('Nikopol', 'Никополь'),
    ('Kremenchuk', 'Кременчуг'),
    ('Simferopol', 'Симферополь'),
    ('Brovary', 'Бровары'),
    ('Khmelnitsky', 'Хмельницкий'),
    ('Pavlohrad', 'Павлоград'),
    ('Chernivtsi', 'Черновцы'),

]
