# Generated by Django 4.2.2 on 2023-07-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
