# Generated by Django 4.2.2 on 2023-07-14 11:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='bboard_prod_title_3d331c_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['title'], name='bboard_prod_title_89a926_btree'),
        ),
    ]
