# Generated by Django 4.2.2 on 2023-07-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_remove_product_bboard_prod_title_3d331c_gin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='bboard_prod_title_89a926_btree',
        ),
    ]
