# Generated by Django 4.2.2 on 2023-07-14 11:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_remove_product_bboard_prod_title_89a926_btree'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['image'], name='bboard_imag_image_e81baf_btree'),
        ),
    ]
