# Generated by Django 4.2.2 on 2023-07-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_image_bboard_imag_image_e81baf_btree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
