# Generated by Django 4.2.2 on 2023-07-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
