# Generated by Django 4.2.2 on 2023-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True, verbose_name='URL'),
        ),
    ]
