# Generated by Django 4.2.2 on 2023-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0023_alter_order_email_ordercart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercart',
            options={'verbose_name': 'Заказ с корзины', 'verbose_name_plural': 'Заказы c корзины'},
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
