# Generated by Django 4.2.2 on 2023-10-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0025_chat_receiver_unread_chat_sender_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
